services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    networks:
      - inception
    env_file: .env
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always

  nginx:
    build: requirements/nginx
    container_name: nginx
    image: nginx:inception
    restart: always
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    env_file: .env
    depends_on:
      - wordpress

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    image: wordpress:inception
    restart: always
    expose:
      - "9000"
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html
    env_file: .env
    depends_on:
      - mariadb

volumes:
  mariadb_volume:
    driver_opts:
      o: bind
      device: /Users/user/data/mariadb
      type: none

  wordpress_volume:
    driver_opts:
      type: bind
      o: bind
      device: /Users/user/data/wordpress

networks:
  inception:
    driver: bridge
