services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    image: mariadb:inception
    restart: always
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file: .env

  # nginx:
  #   build: requirements/nginx
  #   container_name: nginx
  #   image: nginx:inception
  #   restart: always
  #   ports:
  #     - "443:443"
  #   networks:
  #     - inception
  #   volumes:
  #     - wordpress:/var/www/html
  #   env_file: .env
  #   depends_on:
  #     - wordpress

  # wordpress:
  #   build: requirements/wordpress
  #   container_name: wordpress
  #   image: wordpress:inception
  #   restart: always
  #   expose:
  #     - "9000"
  #   networks:
  #     - inception
  #   volumes:
  #     - wordpress:/var/www/html
  #   env_file: .env
  #   depends_on:
  #     - mariadb

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /Users/user/data/wordpress

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: /Users/user/data/mariadb
